name: Lint and test

on: push

env:
  DEVBOX_USE_VERSION: '0.16.0'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.15.0
      - name: Run the lint script
        run: devbox run lint
      - name: Run the test script
        run: devbox run test
